# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('minimum_toefl', models.IntegerField()),
                ('minimum_gre', models.IntegerField()),
                ('other_prerequisite', models.CharField(max_length=5000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Field')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/university/')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.University'),
        ),
    ]
