# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_remove_university_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(default='', upload_to='images/field/'),
            preserve_default=False,
        ),
    ]
