# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_program_minimum_gre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'رشته'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'برنامه'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'دانشگاه'},
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='field',
            name='image',
            field=models.ImageField(upload_to='images/field/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(choices=[('M', 'Master'), ('P', 'PHD')], max_length=1, verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='program',
            name='minimum_toefl',
            field=models.IntegerField(verbose_name='حداقل تافل'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='program',
            name='other_prerequisite',
            field=models.CharField(max_length=5000, verbose_name='ساید پیشنیازها'),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(max_length=50, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(upload_to='images/university/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.IntegerField(verbose_name='رتبه'),
        ),
    ]
